# This file was generated by GoReleaser. DO NOT EDIT.
cask "hydra-bin" do
  version "1.2.8"

  on_macos do
    on_intel do
      sha256 "9d60df8c84589ca39fdc01501fb1ea66d26b20c16ee41d91ff76c153066e2e84"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d9090a49ec8ef9f43a5f930e861decdf5b4bda02843cde2e20ca0c53c0255686"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "c9998f1c7ad5f523b64b5f08dafa83f794ff0aa9dbe9dfd89b328b72dcbb937a"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "bd7cdf7eec60cb6933f32f97731c2c634038570675d49cca0b9de7320f9c358f"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hydra-bin"
  desc "Hydra GitOps CLI binary for Kubernetes cluster management"
  homepage "https://hydra-gitops.org/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hydra"

  # No zap stanza required

end
