# This file was generated by GoReleaser. DO NOT EDIT.
cask "hydra-bin" do
  version "1.2.2"

  on_macos do
    on_intel do
      sha256 "268744a83a6cab099c1770c2e544a08420c6cc4c0a484a093650e223e155a77a"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9ab8f8c9a5c1a4752001cbf95b3dca8426fb8015971607d824dc644d176db70"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ed372214d696a9ab06a6959e37e4d9e6cacb9a99785e9114e9f282289fe78594"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "603a92a6f9e3a89ca4e1620f77ba7fc04981564ed53cf61ff3cf472d077708ed"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hydra-bin"
  desc "Hydra GitOps CLI binary for Kubernetes cluster management"
  homepage "https://hydra-gitops.org/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hydra"

  # No zap stanza required

end
