# This file was generated by GoReleaser. DO NOT EDIT.
cask "hydra-bin" do
  version "1.2.3"

  on_macos do
    on_intel do
      sha256 "c863c370fbf7e8ffc8024e118a3191b58813637f535e3fb6e0a8730062fa23bb"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "767857c0bd6e8e680c9f218f417a9f6780c8c51d3c95223c42638acca4b6173d"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "82c6a47742628dcfdcdfdf5cf0d3edca33b3e9d9aad902837533ff484fca70ec"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5b7b63ef1810f223128d52e609637542523cfab8cc036ce8e82c633e3357b9c9"
      url "https://github.com/drieks/hydra/releases/download/v#{version}/hydra_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hydra-bin"
  desc "Hydra GitOps CLI binary for Kubernetes cluster management"
  homepage "https://hydra-gitops.org/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hydra"

  # No zap stanza required

end
